FROM ubuntu:20.04

RUN apt-get update && apt-get install -y openssh-server && apt-get install -y sudo && apt-get install -y vim && apt-get install -y gcc && apt-get install -y nano && apt-get install -y php && apt-get install -y python && apt-get install -y libcap2-bin

RUN useradd -m user1 && useradd -m user2 && useradd -m user3 && useradd -m user4 && useradd -m user5 && useradd -m user6 && useradd -m user7 && useradd -m user8 && useradd -m user9

RUN echo "level1\nlevel1" | passwd user1
RUN echo "Jg2u5NQJQr1VHZMq7q\nJg2u5NQJQr1VHZMq7q" | passwd user2
RUN echo "tZjTSRR7ldX4QhhSuH\ntZjTSRR7ldX4QhhSuH" | passwd user3
RUN echo "NKYeTRXHTsyZ6rBGPU\nNKYeTRXHTsyZ6rBGPU" | passwd user4
RUN echo "ANWztui2HEzoim2yVa\nANWztui2HEzoim2yVa" | passwd user5
RUN echo "4YPzewTX059t74q4Jn\n4YPzewTX059t74q4Jn" | passwd user6
RUN echo "xgIBql5SntiJFUOsK0\nxgIBql5SntiJFUOsK0" | passwd user7
RUN echo "0SvPdlnE1IbK5hSy6c\n0SvPdlnE1IbK5hSy6c" | passwd user8
RUN echo "xmz74ALNN1wNMKDRK1\nxmz74ALNN1wNMKDRK1" | passwd user9

RUN echo 'user1 ALL=(user2) NOPASSWD:/bin/vim' >> /etc/sudoers
RUN echo "flag-EB89947CEFDA4F2F31B0BB541D8D392D" > /home/user2/flag && chown user2:user2 /home/user2/flag && chmod 400 /home/user2/flag

RUN echo 'user2 ALL=(user3) NOPASSWD:/bin/find' >> /etc/sudoers
RUN echo "flag-DF3C94F27993CB778036E4394E183097" > /home/user3/flag && chown user3:user3 /home/user3/flag && chmod 400 /home/user3/flag

RUN echo 'user3 ALL=(user4) NOPASSWD:/bin/ssh' >> /etc/sudoers
RUN echo "flag-13F2D5428903168083909B846838DB1A" > /home/user4/flag && chown user4:user4 /home/user4/flag && chmod 400 /home/user4/flag

RUN echo 'user4 ALL=(user5) NOPASSWD:/bin/awk' >> /etc/sudoers
RUN echo "flag-0A2CA5335B11E36841272E51B099FB03" > /home/user5/flag && chown user5:user5 /home/user5/flag && chmod 400 /home/user5/flag

RUN echo 'user5 ALL=(user6) NOPASSWD:/bin/php' >> /etc/sudoers
RUN echo "flag-51900FA8F37F37F56127D1F4470D9409" > /home/user6/flag && chown user6:user6 /home/user6/flag && chmod 400 /home/user6/flag

RUN echo 'user6 ALL=(user7) NOPASSWD:/bin/python' >> /etc/sudoers
RUN echo "flag-2F47C014E8398E4F3FF9F74418645904" > /home/user7/flag && chown user7:user7 /home/user7/flag && chmod 400 /home/user7/flag

RUN echo 'user7 ALL=(user8) NOPASSWD:/bin/tar' >> /etc/sudoers
RUN echo "flag-66032EAC282EF9E1D142407D6949C4C3" > /home/user8/flag && chown user8:user8 /home/user8/flag && chmod 400 /home/user8/flag

RUN echo 'user8 ALL=(root) NOPASSWD:/sbin/setcap' >> /etc/sudoers
RUN echo "flag-D51DE4CE11DC339C78F4AA38A2604331" > /home/user9/flag && chown user9:user9 /home/user9/flag && chmod 000 /home/user9/flag

EXPOSE 22
